#!/usr/bin/env ansible-playbook
- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      hostname: 192.168.0.101
      username: "admin"
      password: "Netapp1!"
      https: true
      validate_certs: false
      use_rest: always
  collections:
  - netapp.ontap
  tasks:
  - name: Initial Setup Cpeer
  na_ontap_cluster_peer:
    state: present
    dest_intercluster_lifs: "192.168.0.123,192.168.0.124"
    passphrase: "P@ssw0rd"
    <<: *input
- hosts: localhost
  gather_facts: false
  vars:
    input2: &input2
      hostname: 192.168.0.102
      username: "admin"
      password: "Netapp1!"
      https: true
      validate_certs: false
      use_rest: always
  collections:
  - netapp.ontap
  tasks:
  - name: Initial Setup Cpeer
  na_ontap_cluster_peer:
    state: present
    source_intercluster_lifs: "192.168.0.121,192.168.0.122"
    passphrase: "P@ssw0rd"
    <<: *input2
