#!/usr/bin/env ansible-playbook
- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      hostname: 192.168.0.102
      username: "admin"
      password: "Netapp1!"
      https: true
      validate_certs: false
      use_rest: always
  collections:
  - netapp.ontap
  tasks:
  - name: Create cluster2 aggrs
    na_ontap_aggregate:
      state: present
      service_state: online
      name: "{{ item.aggr }}"
      nodes: "{{ item.node }}"
      disk_count: 12
      <<: *input
    loop:
    - { aggr: 'cluster2_01_aggr', node: 'cluster2-01' }
    - { aggr: 'cluster2_02_aggr', node: 'cluster2-02' }
