#!/usr/bin/env ansible-playbook
- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      hostname: 192.168.0.101
      username: "admin"
      password: "Netapp1!"
      https: true
      validate_certs: false
      use_rest: always
  collections:
  - netapp.ontap
  tasks:
  - name: Remove SVM peer
    na_ontap_vserver_peer:
      state: absent
      peer_vserver: svmDst
      vserver: svmSrc
      <<: *input
  - name: Remove cluster peer
    na_ontap_cluster_peer:
      state: absent
      source_cluster_name: cluster1
      dest_cluster_name: cluster2
      dest_hostname: 192.168.0.102
      <<: *input
  - name: Remove IC LIFs
    na_ontap_interface:
      state: absent
      interface_name: "{{ item.icname }}"
      <<: *input
    loop:
    - { icname: 'ic1' }
    - { icname: 'ic2' }
  - name: Add job schedule
    na_ontap_job_schedule:
      state: present
      name: "mirror5min"
      job_minutes: 2,7,12,17,22,27,32,37,42,47,52,57
      <<: *input
  - name: Add Snapshot policy
    na_ontap_snapshot_policy:
      state: present
      vserver: "svmSrc"
      name: "5minSnapshotPolicy"
      schedule: "mirror5min"
      prefix: "prodSnap5min"
      count: 10
      enabled: true
      <<: *input
  - name: Create volume
    na_ontap_volume:
      state: present
      vserver: "svmSrc"
      aggregate_name: "cluster1_01_SSD_1"
      name: "prodVol1"
      space_guarantee: "none"
      efficiency_policy: default
      size: 5000
      size_unit: "mb"
      snapshot_policy: "5minSnapshotPolicy"
      <<: *input
  - name: Add data
    na_ontap_command:
      command: "set d -c off;run cluster1-01 mkfile 1m /vol/prodVol1/file 2000"
      <<: *input
  - name: Add job schedule 2
    na_ontap_job_schedule:
      state: present
      name: "mirror30min"
      job_minutes: 2,32
      <<: *input
  - name: Add Snapshot policy 2
    na_ontap_snapshot_policy:
      state: present
      vserver: "svmSrc"
      name: "30minSnapshotPolicy"
      schedule: "mirror30min"
      prefix: "prodSnap30min"
      snapmirror_label: "30min"
      count: 5
      enabled: true
      <<: *input
  - name: Create volume 2
    na_ontap_volume:
      state: present
      vserver: "svmSrc"
      aggregate_name: "cluster1_01_SSD_1"
      name: "prodVol2"
      space_guarantee: "none"
      efficiency_policy: default
      size: 5000
      size_unit: "mb"
      snapshot_policy: "30minSnapshotPolicy"
      <<: *input
  - name: Create volume 3
    na_ontap_volume:
      state: present
      vserver: "svmSrc"
      aggregate_name: "cluster1_01_SSD_1"
      name: "prodVol3"
      space_guarantee: "none"
      efficiency_policy: default
      size: 5000
      size_unit: "mb"
      snapshot_policy: "30minSnapshotPolicy"
      <<: *input
  - name: Add Job Schedule 3
    na_ontap_job_schedule:
      state: present
      name: "mirror30min2"
      job_minutes: 7,37
      <<: *input
  - name: Add Snapshot policy 3
    na_ontap_snapshot_policy:
      state: present
      vserver: "svmSrc"
      name: "30minSnapshotPolicy2"
      schedule: "mirror30min2"
      prefix: "prodSnap30min"
      snapmirror_label: "30min"
      count: 5
      enabled: true
      <<: *input
  - name: Create volume 4
    na_ontap_volume:
      state: present
      vserver: "svmSrc"
      aggr_list:
      - "cluster1_01_SSD_1"
      - "cluster1_02_SSD_1"
      aggr_list_multiplier: 2
      efficiency_policy: none
      name: "prodFGvol"
      space_guarantee: "none"
      snapshot_policy: "30minSnapshotPolicy2"
      <<: *input
- hosts: localhost
  gather_facts: false
  vars:
    input2: &input2
      hostname: 192.168.0.102
      username: "admin"
      password: "Netapp1!"
      https: true
      validate_certs: false
      use_rest: always
  collections:
  - netapp.ontap
  tasks:
  - name: Remove IC LIFs
    na_ontap_interface:
      state: absent
      interface_name: "{{ item.icname }}"
      <<: *input2
    loop:
    - { icname: 'ic1' }
    - { icname: 'ic2' }
