#!/usr/bin/env ansible-playbook
- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      hostname: 192.168.0.101
      username: "admin"
      password: "Netapp1!"
      https: true
      validate_certs: false
      use_rest: always
  collections:
  - netapp.ontap
  tasks:
  - name: Remove SVM peer
    na_ontap_vserver_peer:
      state: absent
      peer_vserver: svmDst
      vserver: svmSrc
      <<: *input
  - name: Remove cluster peer
    na_ontap_cluster_peer:
      state: absent
      source_cluster_name: cluster1
      dest_cluster_name: cluster2
      dest_hostname: 192.168.0.102
      <<: *input
  - name: Down IC LIFs
    na_ontap_interface:
      state: present
      interface_name: "{{ item.icname }}"
      vserver: cluster1
      admin_status: down
      <<: *input
    loop:
    - { icname: 'ic1' }
    - { icname: 'ic2' }
  - name: Remove IC LIFs
    na_ontap_interface:
      state: absent
      interface_name: "{{ item.icname }}"
      vserver: cluster1
      <<: *input
    loop:
    - { icname: 'ic1' }
    - { icname: 'ic2' }
- hosts: localhost
  gather_facts: false
  vars:
    input2: &input2
      hostname: 192.168.0.102
      username: "admin"
      password: "Netapp1!"
      https: true
      validate_certs: false
      use_rest: always
  collections:
  - netapp.ontap
  tasks:
  - name: Down IC LIFs
    na_ontap_interface:
      state: present
      interface_name: "{{ item.icname }}"
      vserver: cluster2
      admin_status: down
      <<: *input2
    loop:
    - { icname: 'ic1' }
    - { icname: 'ic2' }
  - name: Remove IC LIFs
    na_ontap_interface:
      state: absent
      interface_name: "{{ item.icname }}"
      vserver: cluster2
      <<: *input2
    loop:
    - { icname: 'ic1' }
    - { icname: 'ic2' }
