#!/usr/bin/env ansible-playbook
- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      hostname: 192.168.0.101
      username: "admin"
      password: "Netapp1!"
      https: true
      validate_certs: false
      use_rest: always
  collections:
  - netapp.ontap
  tasks:
  - name: Create volume sync source
    na_ontap_volume:
      state: present
      vserver: "svmSrc"
      aggregate_name: "cluster1_01_SSD_1"
      name: "volSync"
      space_guarantee: "none"
      efficiency_policy: default
      size: 3000
      size_unit: "mb"
      snapshot_policy: "5minSnapshotPolicy"
      <<: *input
  - name: SE Edit
    na_ontap_command:
      command: "set d -c off;sis off volSync"
      <<: *input
