# Cheating doesn't help you learn.
- hosts: localhost
  gather_facts: false
  vars:
    input2: &input2
      hostname: 192.168.0.102
      username: "admin"
      password: "Netapp1!"
      https: true
      validate_certs: false
      use_rest: always
  collections:
  - netapp.ontap
  tasks:
  - name: Add data
    na_ontap_command:
      command: "set d -c off;snapmirror break {* -policy-type mirror-vault}"
      <<: *input2
