#!/usr/bin/env ansible-playbook
#Cheating doesn't help you learn.
- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      hostname: 192.168.0.101
      username: "admin"
      password: "Netapp1!"
      https: true
      validate_certs: false
      use_rest: always
  collections:
  - netapp.ontap
  tasks:
  - name: Add data
    na_ontap_command:
      command: "set d -c off;vol modify -vserver svmProd -volume volHR -vserver-dr-protection unprotected"
      <<: *input
- hosts: localhost
  gather_facts: false
  vars:
    input2: &input2
      hostname: 192.168.0.102
      username: "admin"
      password: "Netapp1!"
      https: true
      validate_certs: false
      use_rest: always
  collections:
  - netapp.ontap
  tasks:
  - name: Add data
    na_ontap_command:
      command: "set d -c off;snapmirror update svmDR:"
      <<: *input2
