#!/usr/bin/env ansible-playbook
- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      hostname: 192.168.0.101
      username: "admin"
      password: "Netapp1!"
      https: true
      validate_certs: false
      use_rest: always
  collections:
  - netapp.ontap
  tasks:
  - name: Create SVM
    na_ontap_svm:
      state: present
      name: svmProd
      root_volume: svmProd_root
      root_volume_aggregate: cluster1_01_SSD_1
      root_volume_security_style: unix
  - name: Create volume 1
    na_ontap_volume:
      state: present
      vserver: "svmSrc"
      aggregate_name: "cluster1_01_SSD_1"
      name: "volHR"
      space_guarantee: "none"
      efficiency_policy: default
      size: 100
      size_unit: "mb"
      snapshot_policy: "5minSnapshotPolicy"
      <<: *input
  - name: Create volume 1
    na_ontap_volume:
      state: present
      vserver: "svmSrc"
      aggregate_name: "cluster1_01_SSD_1"
      name: "volHR"
      space_guarantee: "none"
      efficiency_policy: default
      size: 100
      size_unit: "mb"
      snapshot_policy: "5minSnapshotPolicy"
      <<: *input
