#!/usr/bin/env ansible-playbook
- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      hostname: 192.168.0.101
      username: "admin"
      password: "Netapp1!"
      https: true
      validate_certs: false
      use_rest: always
  collections:
  - netapp.ontap
  tasks:
  - name: Create SVM
    na_ontap_svm:
      state: present
      name: svmProd
      <<: *input
  - name: Add Snapshot policy
    na_ontap_snapshot_policy:
      state: present
      vserver: "svmProd"
      name: "5minSnapshotPolicy"
      schedule: "mirror5min"
      prefix: "prodSnap5min"
      count: 10
      enabled: true
      <<: *input
  - name: Create volume 1
    na_ontap_volume:
      state: present
      vserver: "svmProd"
      aggregate_name: "cluster1_01_SSD_1"
      name: "volHR"
      space_guarantee: "none"
      efficiency_policy: default
      size: 100
      size_unit: "mb"
      snapshot_policy: "5minSnapshotPolicy"
      <<: *input
  - name: Create volume 2
    na_ontap_volume:
      state: present
      vserver: "svmProd"
      aggregate_name: "cluster1_02_SSD_1"
      name: "volHR"
      space_guarantee: "none"
      efficiency_policy: default
      size: 100
      size_unit: "mb"
      snapshot_policy: "5minSnapshotPolicy"
      <<: *input
  - name: Create Data LIF
    na_ontap_interface:
      state: present
      interface_name: dataLif1
      protocols:
      - nfs
      - cifs
      home_port: e0d
      home_node: cluster1-01
      service_policy: "default-data-files"
      address: 192.168.0.141
      netmask: 255.255.255.0
      vserver: svmProd
      <<: *input
