#!/usr/bin/env ansible-playbook
- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      hostname: 192.168.0.101
      username: "admin"
      password: "Netapp1!"
      https: true
      validate_certs: false
      use_rest: always
  collections:
  - netapp.ontap
  tasks:
  - name: Add data
    na_ontap_command:
      command: "set d -c off;run cluster1-01 mkfile 1m /vol/prodVol1/file 2000"
      <<: *input
